
package:
  name: public-decomp-wt 
  version: 0.1

source:
  - path: ../

build:
  number: 0

requirements:
  build:
    - cmake  # [win]
    - pkg-config >=0.21  # [not win]
    - {{ compiler('c') }}  # [not win] 
    - {{ compiler('cxx') }}  # [not win]
    - vc  # [win]
    - vs2015_runtime=14.16  # [win]
  host:
          #  - m2-patch  # [win]
          #    - python=3.6
          #    - gdal=={{ gdal_version }}
  run:
          #    - python=3.6
          #    - gdal=={{ gdal_version }}

about:
  home: http://www.eumetsat.int/
  license: Apache License 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: The PublicDecompWT tool can be build in Windows, Linux and Solaris. Note that it only decompresses compressed XRIT files. It includes a decoder for JPEG, WT and T4. 

