name: "Pip"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest]  # , windows-latest]
        python-version: ["3.6", "3.10", "pypy-3.7"]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pybind11 % wheel
        run: pip install --verbose wheel "pybind11[global]"

      - name: Set min macOS version
        if: matrix.python-version == 'pypy-3.7' && runner.os == 'macOS'
        run: |
          echo "MACOS_DEPLOYMENT_TARGET=10.9" >> $GITHUB_ENV

      - name: Build and install
        run: pip install --verbose .[test]

      - name: Run Tests
        run: cd tests && pytest
