name: "Pip"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "pypy-3.7"]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build and install
        run: pip install --verbose .[test]

      - name: Run Tests
        run: cd tests && pytest
