name: CI build

on:
  push:
    branches:
      - 'main'

jobs:
  CIBW:
    uses: sbrodehl/pyxRITDecompress/.github/workflows/cibuildwheel.yml@main
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}