name: "CI build"

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '* * * * */2'

jobs:
  CIBW:
    uses: sbrodehl/pyPublicDecompWT/.github/workflows/cibuildwheel.yml@main
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
